# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: ablation-S_x2_down_reallr
model_type: ImageRestorationModel
scale: 2
num_gpu: 2  # fault Gpu=8, batchsize=4
manual_seed: 10

datasets:
  train:
    name: Flickr1024-sr-train
    type: hatPassPairedStereoImageDataset
    dataroot_gt: /home/thinkstation03/zjt/NAFNet-data/train/v2finetuneHAT-L_sisr_withreallr_patches_x2/
    dataroot_lq: /home/thinkstation03/zjt/NAFNet-data/train/v2finetuneHAT-L_sisr_withreallr_patches_x2/
    dataroot_reallq: /home/thinkstation03/zjt/NAFNet-data/train/v2finetuneHAT-L_sisr_withreallr_patches_x2/
    io_backend:
      type: disk

    gt_size_h: 60
    gt_size_w: 180
    use_hflip: true
    use_vflip: true
    use_rot: false
    flip_RGB: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16  # default 4,, ffb :14,, 16block时＝４
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Flickr1024-sr-test
    type: hatPassPairedStereoImageDataset  # 读数据的类名
    dataroot_gt: /home/thinkstation03/zjt/NAFNet-data/test/Flickr1024/hr
    dataroot_lq: /home/thinkstation03/zjt/NAFNet-data/test_finetuneHAT-L/Flickr1024/lr_x2
    dataroot_reallq: /home/thinkstation03/zjt/NAFNet-data/test_finetuneHAT-L/Flickr1024/lr_x2
    io_backend:
      type: disk

# network structures
network_g:
  type: NewsimpleFFCwithHAT_down_withCSAM_SSR    
        # model/archs/NAFSSR_arch.py --> class(NAFSSR)  , default: NAFSSR, NewSSR, NewsimpleFFCSSR
  up_scale: 2
  width: 64
  num_blks: 28  # default: 32,, 0.1,0.2是16，  0.3是28
  drop_path_rate: 0.1
  train_size: [1, 12, 60, 180]
  drop_out_rate: 0.

# path
path:
  pretrain_network_g: ~ #/home/thinkstation03/zjt/NAFNet-ALL/experiments/NAFNetSR-S_x2_simpleffb_finetuneHatSR_down__withReallr_v0.1.2/models/net_g_latest.pth # 不用的就设为：~
  strict_load_g: false
  resume_state: ~
  save_info_outer_main: true

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 3e-3    # default: !!float 3e-3
    weight_decay: !!float 0
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 100000  # fault 100000
    eta_min: !!float 1e-7

  total_iter: 100000  # need epoch = 10.732,, 
  warmup_iter: -1 # no warm up
  mixup: false

# 图片计算方式：N = 298143（图片块总数）
# S = N/batchsize
# epoch = total_iter / S = total_iter * batchsize / N
# total_iter = epoch * N / batchsize
# 如果需要保持训练同样epoch数目， 需要改变total_iter数量 

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.
    reduction: mean

  # finetune
  finetune_byjintao:
    flag: false # or false  [true：微调下面指定， false：微调全量]
    need_keys: ['ffcSimBlock', 'conv3_new']
    # need_keys: ['body.29', 'body.30', 'body.31']  # 这里记得灵活改写

# validation settings
val:
  val_freq: !!float 5e3  # fault: 2e4，，　ｂｌｏｃｋ＝１６－－》　２ｅ３
  save_img: false
  trans_num: 1

  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_skimage_ssim

# logging settings
logger:
  print_freq: 200  # fault 200
  save_checkpoint_freq: !!float 5e3   # fault:1e4  # block=16==> save=5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
